### ISSUE TITLE
Mixins for Typography

### ISSUE THREAD

**Issue by shaunbent** [bbc/gel-typography#13]
Whilst we could advocate using the GEL Typography classes within markup is the most effective way of applying the typography to your codebase and offers complete separation of concerns. There are certain cases where we either can't use this or need to do something a little more bespoke.

To facilitate these edge cases we should expose some helper mixins so that typography can be applied consistent way. Something like this:

``` sass
.some-component {
    @include gel-pica;
}
```

This should output the following:

``` css
.some-component {
      font-size: 15px;
      line-height: 20px;
}

@media all and (min-width: 20em) {
    .some-component {
       font-size: 16px;
       line-height: 22px;
    }
}

@media all and (min-width: 37.5em) {
    .some-component {
       font-size: 18px;
       line-height: 24px;
    }

    .no-touch .some-component {
       font-size: 16px;
       line-height: 22px;
    }
}
```

We should also investigate a way that you can output a specific typography group, thus allowing you to change the typography group at different breakpoints. Something like:

``` sass
.some-component {
    @include gel-double-pica;

    @if $enhanced {
        @include mq($from: gel-bp-m) {
            @include gel-pica;
        }
    }
}
```

We would really need to think about this though as we need to ensure the output is correct. You might need to be able to specify the specific typography group size you want output. Maybe something like this:

``` scss
.some-component {
    @include gel-double-pica(group-a);
}
```

We need to remember if you output `group-c` or `group-d` these two are always linked. If you output one you should always output the other.
### Extends

You could achieve a similar thing with the existing codebase but this would involve using the Sass `@extend` feature which is probably not appropriate for this kind of relationship:
- [@extend: A Fool’s Gold](http://oliverjash.me/2012/09/07/methods-for-modifying-objects-in-oocss.html)
- [When to use @extend; when to use a mixin](http://csswizardry.com/2014/11/when-to-use-extend-when-to-use-a-mixin/)
- [Sass Mixins vs Extends: The Data](https://tech.bellycard.com/blog/sass-mixins-vs-extends-the-data/)

Whilst this will produce more output compared to the use of an `@extend` research has shown that compression will be more effective on this repeating data, thus negating the page weight of any additional output. Avoiding the use of `@extend` also stops any false relationships being forged between code elements.
